### ISSUE TITLE
Team Drive Option

### ISSUE THREAD

**Issue by jgo42** [pownthep/Vibe#7]
Need to add team drive access

**Comment by askfriends** [comment]
+1

**Comment by pownthep** [comment]
Could you elaborate more on this features?

**Comment by askfriends** [comment]
> Could you elaborate more on this features?

we mean to add google team drive aka shared drive support so that we can build streaming server using our team drive.

**Comment by pownthep** [comment]
I will be adding a feature where you can browse and stream videos in your shared drive.
